### ISSUE TITLE
Estilos para GeJSON

### ISSUE THREAD

**Issue by sigdeletras** [sitna/api-sitna#10]
Saludos!

He revisado la documentación de la API y no me ha quedado claro si puedo aplicar en estilo propio a capas de vectorial de tipo GEOJSON.

Veo que existen opciones de simbología de distintas geometrías, pero como digo no me queda claro si son aplicables a las capas vectoriales o se definen en el config.json y son características globales.

Muchas gracias

**Comment by flacunza** [comment]
Hola, sigdeletras.

Los estilos de las capas se pueden aplicar de manera global, distinguiendo por tipo de geometría, mediante la propiedad _styles_ en las opciones de mapa, tal como viene aquí: http://sitna.tracasa.es/api/doc/global.html#MapOptions

Aquí puedes ver un ejemplo con una capa GeoJSON a la que se le ha cambiado el color por defecto de las entidades vectoriales con geometría polígonal: https://jsfiddle.net/fLjv1rc5/1/

Un saludo.

**Comment by sigdeletras** [comment]
Saludos Fernando.

Vamos a escribir una entrada sencilla con un ejemplo de usos de la API en el blog de Geoinnova, creo que esto es un buen aporte a la documentación oficial.

Tenemos también en mente un desarrollo desde QGIS que pueda automatizar la configuración del visor. Seguro que surgen más consultas.

Gracias de nuevo por la rapidez en la respuesta.

Un saludo Patricio

**Comment by flacunza** [comment]
Nos parece muy interesante ese desarrollo QGIS. Espero saber más de ello en el futuro.

Un saludo.
