### ISSUE TITLE
integracion api sitna web

### ISSUE THREAD

**Issue by geopamplona** [sitna/api-sitna#4]
Buenos días, 

Intento incluir API SITNA en un proyecto web, y me encuentro con los siguientes errores:
- carpeta TC/Control debería ser TC/control; por defecto se busca mal la carpeta o en el repositorio la capeta tiene mal el nombre.
- la capreta tc/layout no se carga correctamente; TC/layout mal referenciado
Modifico TC/Map.js; comento las líneas 790 y 791 para que busque correctamente los recursos
-  en tcmap.js cambiar      TC.isDebug = false;
- idiomas mal referenciados; fallo al cargar el fichero de idiomas por defecto: es_ES.json
Por defecto busca "undefinedresources/es_ES.json"
Intento corregir este problema modificando la funcion loadResources y TC.apiLocation pero no encuentro el problema. 
Por favor, necesitaría ayuda para integrar correctamente la herramienta, dado la escaza documentación sobre este tema disponible online.

Buen trabajo  y muchas gracias
Un saludo !

Alejo Sarfson

**Comment by flacunza** [comment]
Hola, Alejo:

Respecto al nombre de la carpeta `control`, estás en lo cierto y ya la hemos cambiado.
Respecto a la ruta del layout y de los idiomas, parece que es porque en tu aplicación no se inicializa el valor de `TC.apiLocation` correctamente. La API asigna el valor a partir de la ruta del script de la siguiente manera:
```
if (document.currentScript) {
    script = document.currentScript;
}
else {
    var scripts = document.getElementsByTagName('script');
    script = scripts[scripts.length - 1];
}
var src = script.getAttribute('src');
TC.apiLocation = src.substr(0, src.lastIndexOf('/') + 1);
```
Si este código te está fallando, nos gustaría saberlo, no obstante puedes evitar el problema instanciando un objeto `TC` en un script anterior al de la API, de manera similar a la siguiente:
```
<script  type="text/javascript">
TC = {
    apiLocation: '/ruta_api_sitna/'
};
</script>
```
Respecto a al valor de `TC.isDebug`, es _true_ porque el código publicado es el de desarrollo. Acabamos de publicar una carpeta build donde está el código en versión de producción creado con el gulpfile. Los archivos *.min.js vienen con `TC.isDebug = false`. Tienes más información al respecto en la sección _Direcciones de la API_ en [http://sitna.navarra.es/api/doc/](http://sitna.navarra.es/api/doc/).

¡Gracias por el feedback!

Un saludo.
Fernando Lacunza

**Comment by geopamplona** [comment]
Buenos días Fernando, 

Con la librería construida funciona todo correctamente; perfecto que esté en el repositorio.
Las correcciones que indicas también funciona todo, ahora si puedo desplegar la librería correctamente.
En el futuro intento construirla con gulp.

Estaré pendiente de las actualizaciones para daros algo de feedback !

Muchas gracias!  
Alejo Sarfson

**Comment by flacunza** [comment]
Hola, Alejo:

Quiero hacer una recomendación: En la medida de lo posible usa los objetos que están dentro del espacio de nombres SITNA en vez de los del espacio de nombres TC. Los de SITNA son los que están documentados y son los que van a mantener la compatibilidad hacia atrás. No nos vamos a comprometer a que no haya cambios en TC en las futuras versiones de la API que rompan algún desarrollo.

Un saludo,
Fernando Lacunza

**Comment by geopamplona** [comment]
Buenas tardes Fernando, 
Tendre en cuenta tu recomendación para mis desarrollos, muchas gracias !
Utilizando la libreria construida no tengo problemas.

Muchas gracias !
Un saludo !
Alejo Sarfson

**Comment by geopamplona** [comment]
Buenos días, 

Sigo comentando por aqui por no abrir otro issue.
Utilizo la última versión api sitna construida y tengo problemas para dirigir correctamente los recursos; es decir, busca recursos en una carpeta que no es correcta.
![imagen](https://cloud.githubusercontent.com/assets/25028240/24697332/110fc37c-19ed-11e7-8030-00a56cbbcf51.png)

Lo estoy solucionando modificando código a mano para que no busque en la carpeta raiz, sino en la que se ejecuta el script constructor.

Aun asi sigue mapeando mal la carpeta resources con los textos.
![imagen](https://cloud.githubusercontent.com/assets/25028240/24697428/6609127a-19ed-11e7-918c-468628bd0731.png)
![imagen](https://cloud.githubusercontent.com/assets/25028240/24697446/7b5f38f2-19ed-11e7-8106-5e15f56a07e0.png)

Por otro lado, tambien da problemas la integración css con el layout responsive. 
En el fichero style.css se declaran estilos globales que me rompen la integracion en otros entornos.
Convendría tener un layout que sea facilmente integrable en otros entornos; que declare css dentro de la capa del mapa (Sobre esto he visto mejoras respecto a versiones anteriores). El layout minimal para esto es demasiado basico. 
Este punto lo he solucionado comentando codigo css que afecte a estilos globales.

Despues de todo, el principal issue que tengo es a la hora de mapear resources/es_ES.json en esta nueva version y siguiendo la idea del issue anterior intento solucionar esto sin cambiar apiLocation durante ejecución.
Dado que es un tema recurrente en las ultimas versiones lo comento por aqui.

pd: si necesitais más información puedo aportar más pantallazos
Muchas gracias !
