### ISSUE TITLE
build api-sitna with gulp

### ISSUE THREAD

**Issue by geopamplona** [sitna/api-sitna#5]
Hola, 

Construyo el proyecto con Gulp y obtengo el siguiente error:

```
> c:\Users\asarfson\Documents\GitHub\api-sitna>gulp
> [12:05:10] Using gulpfile c:\Users\asarfson\Documents\GitHub\api-sitna\gulpfile.js
> [12:05:10] Starting 'unitTests'...
> [12:05:10] Starting 'e2eTests'...
> [12:05:10] Finished 'unitTests' after 16 ms
> events.js:160
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn casperjs ENOENT
>     at exports._errnoException (util.js:1020:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
>     at onErrorNT (internal/child_process.js:376:16)
>     at _combinedTickCallback (internal/process/next_tick.js:80:11)
>     at process._tickCallback (internal/process/next_tick.js:104:9)
> 
```

Parece que es un error en el fichero evets.js pero este fichero no pertenece al proyecto.
Falla en los test unitarios.

Si construyo sin realizar test todo va correcto, el fallo ocurre en la task por defecto.
`gulp noTests`

Un saludo !

**Comment by flacunza** [comment]
Hola.

Parece que no tienes CasperJS instalado globalmente. Puedes probar a instalarlo globalmente con ```npm install -g casperjs``` o alternativamente modificar el gulpfile para especificar la ruta de casper usando el parámetro ```binPath``` como se indica en <https://www.npmjs.com/package/gulp-casperjs>.

Más información sobre ese error aquí:
https://github.com/SpookyJS/SpookyJS/issues/206
https://github.com/NullRefExcep/gulp-casperjs/issues/8

**Comment by geopamplona** [comment]
Hola, 

Estaria bien disponer del fichero package.json con las dependencias completas para construir correctamente el proyecto.
