### ISSUE TITLE
fallo en listado de capas al añadir markers de grupos diferentes

### ISSUE THREAD

**Issue by geopamplona** [sitna/api-sitna#7]
Hola, 

Reporto un error en el listado de capas de trabajo utilizando API SITNA; el error se puede reproducir facilmente y afecta a la usabilidad de la herramienta.

El fallo de comportamiento se puede comprobar utilizando el siguiente [ejemplo oficial](http://sitna.navarra.es/api/examples/Map.addLayer.2.html)
Partiendo del codigo de ejemplo, lo modifico para añadir markers de una categoría nueva, "Marcadores colgantes 2"; el código quedaría así:
```
   // Crear mapa.
        var map = new SITNA.Map("mapa");

        // Cuando esté todo cargado proceder a trabajar con el mapa.
        map.loaded(function () {
            // Añadir marcadores al grupo "Marcadores colgantes" 
            // cuyo icono se ancle al punto en el centro hacia abajo. 
            // Establecer un icono adecuado.
            var markerOptions = {
                group: "Marcadores colgantes",
                url: "data/colgante.png",
                anchor: [0.5, 0]
            };
            map.addMarker([610887, 4741244], markerOptions);
            map.addMarker([615364, 4657556], markerOptions);

            // Establecer un icono adecuado.
            var markerOptions = {
                group: "Marcadores colgantes 2",
                url: "data/colgante.png",
                anchor: [0.5, 0]
            };
            map.addMarker([610887, 4741244], markerOptions);
			// Centrar el mapa en los marcadores.
			map.zoomToMarkers();
        });
```

En el listado de capas se genera un arbol de capas como el siguiente:

![imagen](https://user-images.githubusercontent.com/25028240/53177447-5d954e80-35f0-11e9-9e4b-86677099f4f1.png)

Veo dos comportamientos raros, por un lado la capa Vectores no permite el despliegue de la capa, es decir, no puedo agrupar los diferentes grupos dentro de la capa Vectores, comportamiento que si ocurre en otras capas.

Por otro lado, si clicko en el espacio entre las dos capas del listado de capas (adjunto imagen para explicarlo mejor, zona amarilla), el listado se pliega rapidamente y no se puede volver a desplegar.

![imagen](https://user-images.githubusercontent.com/25028240/53177943-355a1f80-35f1-11e9-90d4-464abfe98340.png)

Esto ocurre en Firefox Quantum (65.0.1 64bits) y Chrome (72.0.3626.109 (Build oficial) (64 bits)); en ambos el comportamiento es el mismo.

Esto produce problemas cuando se trabaja con markers de diferentes categorias o grupos, que deben ser seleccionables desde el listado de capas de trabajo.

Un saludo !

**Comment by flacunza** [comment]
Reproducido. En breve publicaremos arreglo. ¡Gracias!

**Comment by geopamplona** [comment]
muchas gracias
un saludo !

**Comment by flacunza** [comment]
Hola.

Al final no ha sido "en breve", pero la nueva versión 1.6.0 que acabamos de publicar corrige ese comportamiento.

Un saludo.

**Comment by geopamplona** [comment]
Gracias !
