### ISSUE TITLE
fallo al instanciar dos mapas

### ISSUE THREAD

**Issue by geopamplona** [sitna/api-sitna#9]
Buenos días, 

Estoy intentando montar dos mapas en una misma vista utilizando el siguiente codigo:

	<!DOCTYPE html>
	<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=edge"> 
	</head>
	<body>
		
		<script src="http://sitna.navarra.es/api/"></script>

		<div id="mapa" style="width:500px;height:500px"></div>
		<div id="mapa2" style="width:500px;height:500px"></div>

		<script>
			var map = new SITNA.Map("mapa");
			var map2 = new SITNA.Map("mapa2");
		</script>
		
	</body>
	</html>

El planteamiento es simple, dos divs `mapa` y `mapa2`, con sus dos constructores `new SITNA.Map("mapa")` y `new SITNA.Map("mapa2")`.

Como resultado ninguno de los dos mapas acaba de cargar ya que rompe antes de acabar de cargar. Tampoco funciona si cargo primero un mapa, espero un rato y luego intento cargar otro.

![imagen](https://user-images.githubusercontent.com/25028240/55937874-4fe86680-5c3a-11e9-8fc6-2a4c0852b7f4.png)

**Comment by flacunza** [comment]
Saludos.

Acabamos de publicar la versión 1.6.0 que corrige esta issue. Se puede ver aquí: https://output.jsbin.com/bijisumeje/1

Gracias por el feedback.

**Comment by geopamplona** [comment]
Gracias !
